# Save this as config.yml when you're done.

wiki_url:       # https://[confluence org name].atlassian.net/wiki/rest/api/content/
wiki_user:      # Your username
wiki_pass:      # Your password
wiki_space:     # Space key, found in URL when in space
wiki_parent:    # This is the "parent" page ID where all pages will be written

