# Save this as config.yml when you're done.

space:      # Space key (str)
parent_id:  # Parent page ID, under which all environment pages will go (int)
india_id:   # India page ID, which holds information on India environments
other_docs_id:  # ID for other docs page

